openapi: 3.0.1
info:
  title: Mobile Frontend
  description: Code repo for the mobile frontend demo.
  x-cortex-git:
    github:
      repository: Mooretex/kotlin-firebase
  x-cortex-tag: mobile-frontend
  x-cortex-type: service
  x-cortex-owners:
  - name: mckinsey
    type: GROUP
